---
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: custom-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAsr1f8Pn+yXov10UITfMohHwLFJsvj6O4/JrRxaqLt3igIRcR
rtuPgKxhr2tWmYnTGkB4+XeHj6K+MuCY+u4UW08Jdp8/XWmPdxIyWCQ3yIDpcnvl
hkbZRy9TLsEcPW8dE0v+Q1cSKFf0t5T6ExB/P4E29Mn/24q+ZFslY72Coy+2X3K+
LCtYXgowugaNHC6ZRR3z/2Oi6N+PKVs3MMbhxd7lOyuTem7+qP1KuzNbpiwRg/+c
WE6FQW+Fblj357a26+faVTGbIuimFyEkui0BRh0ppGsFui7YL98miHN/Chi5ikip
cwdKZvNQrPLK+LT4+76QK1T3/M3kgOOl1xEorQIDAQABAoIBAHCElmj0d1gN+x/g
7SFk+RStoawPJRmfT0x1iaiNe/a7kNJD23Xf8a5m1fe/8nwlLydPfthMTqI1KNaO
XL9aMKZqUuLBzPnZAd9LLTYfVp55yHuxUwP8hbsyJ4M/Pa/Oytbi9+UcYunStNL8
jZCCyhgIF7hxkQd7h+9VEWyAWESxLw4o+tG6xySybW7nw0Zogjl3NU/RTBaXUJxH
DCnmnqg7OacOq+ioHSF1lCnbjlVGOuJHrQgfvI0X1kCKZ9a0XKOfAmRfGS1qneWq
O7FRZT+JaFNjcyOiDmBL2YAcMjSzOJsipTDqskJKGwjOc8xw23FQnT+16dt/+s4x
36oXf2ECgYEA205U3SSPmpGpdVb1/3qIEydlXZ8X6FDCJkp7r9EPmLWleCbN/O91
bWaqF9EE0Oavp9cJo3RV1vCRCcIPNGeej8Okp/4v+LElRphNPU+Hh993FM5VrBXB
cxO7bhjD+Y0s/dn/Lq4zqHAVoBSTNk3SyM4rcAd3b3RqOjRP1Be2mcsCgYEA0KVx
0PqRT7KBSI73Biv6Kl3l95RtgqYxH0erAW+Veerh5ZgpP202/MW1Z3BQch7q9oE2
A4PWGgHpiEeP2tMq8j1jFCMShx0Z7UTlRR4Ese/EKjOu8wocK1zO7AnivKJEXApE
Ny9bh98o9mwiPsUqHn4EnUihQlTM9wGXDy3C2GcCf3mk+W2w2fbi1RxBIDKVxOTa
9V744En8gbS7m9/qFryeBSqgW6HxMTF9wNt1FTbKvqRaov4HiZWv2sOO4OAwmcMk
wjBszi8kE4kU8cMQWh0D1wmzadIKP0OVrmFjW1EQ/ePRB7rc5cqIYXZp8z4r7L91
nKKHgbhQ2ptuaNk8Tg0CgYEAg1DNTGiXUiCXy7Hm+ORuw4FrfiHVtpegbP5vOy0e
V6gj2pukwj2bkQViAaMnjlu1J8X018t+0cmIUHQxrtieu+000XStcYo4SiPFZHXb
IJ41yRXUMzSWvBfiR56FLJG4EnGHs2/D3MTwA//Uocr3kk9f2hnfHF9AzOkcSLpV
WlsCgYEAk4r1mnaZ4SOgPR3eBmi7ajC+kiyN2BwQ6pKHc7pUiqGIe9bQ5g1M9XLw
i7EveuIelt0SIjrKvCXEbcoq6W8mq1wVV7kJ7u4HrXhlBUVf3PYRAOkP05XVdrF7
1Bdhj541yzAcCRF9mq6IgGxNUVBotGU5uKnUv0wbdUvc5DOFtVk=
-----END RSA PRIVATE KEY-----
