---
kind: Secret
apiVersion: v1
metadata:
  name: wildcard-cert-secret
  namespace: openshift-ingress
data:
  tls.cert: {{ .Values.wildcardTlsCrt }}
  tls.key: {{ .Values.wildcardTlsKey }}
type: kubernetes.io/tls

