---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-operator
  namespace: openshift-operators
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: acm_build1/operator
    repoURL: https://github.com/r3dact3d/gitops
    targetRevision: ocp4
