---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: selfsigned-api-cert
  namespace: openshift-config
spec:
  secretName: selfsigned-api-cert
  duration: 24h
  renewBefore: 23h
  isCA: false
  subject:
    organizations:
      - blinker
  usages:
    - server auth
    - client auth
  dnsNames:
  - api.{{ .Values.name }}.{{ .Values.wildcardDomain }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
