---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
          - api.{{ .Values.name }}.{{ .Values.wildcardDomain }}
        servingCertificate:
          name: selfsigned-api-cert
