---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.infraID }}
  name: {{ .Values.infraID }}-infra-{{ .Values.region }}a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.infraID }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.infraID }}-infra-{{ .Values.region }}a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.infraID }} 
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: {{ .Values.infraID }}-infra-{{ .Values.region }}a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: node-role.kubernetes.io/infra
          effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: ami-03d9208319c96db0c 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ .Values.infraID }}-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: {{ .Values.region }}a
            region: {{ .Values.region }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ .Values.infraID }}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ .Values.infraID }}-private-{{ .Values.region }}a 
          tags:
            - name: kubernetes.io/cluster/{{ .Values.infraID }}
              value: owned
          userDataSecret:
            name: worker-user-data
