apiVersion: compliance.openshift.io/v1alpha1
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    name: rhcos4-moderate
    kind: Profile
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  name: default
  kind: ScanSetting
kind: ScanSettingBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: nist-moderate
  namespace: openshift-compliance
scanTolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Exists
- key: infra
  value: reserved
  effect: NoSchedule
