---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-deploy
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: openshift-machines-api
    directory:
      recurse: true
    repoURL: https://github.com/r3dact3d/gitops/common-base/openshift-machine-api
    targetRevision: 0.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
