apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: welcome-hooks-2
  namespace: argocd
  labels:
    app: test
spec:
  generators:
  - clusters:
      selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-hooks'
    spec:
      destination:
        namespace: argocd
        server: '{{server}}'
      project: default
      source:
        path: apps/welcome-php/overlays/hooks
        repoURL: 'https://github.com/taiseerhussein/openshift-gitops-examples.git'
        targetRevision: 2.0.3
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
