apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
  name: medium-namespace
  selector:
    matchLabels:
      size: medium  
  resources:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: medium-size  
    spec:
      hard:
        requests.cpu: "4"
        requests.memory: "2Gi"
