---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  project: default
  source:
    path: common-base/openshift-config
    repoURL: https://github.com/r3dact3d/gitops
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../blinker19/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
