apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: test-selfsigned
  namespace: openshift-operators
spec:
  selfSigned: {}
