---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cost-management-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: costmanagement-metrics-operator
    server: https://kubernetes.default.svc
  project: default 
  source:
    path: common-base/cost-management
    repoURL: https://github.com/r3dact3d/gitops
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../blinker19/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-compliance
    server: https://kubernetes.default.svc
  project: default
  source:
    path: common-base/openshift-compliance
    repoURL: https://github.com/r3dact3d/gitops
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../blinker19/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
