---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Infra-MachineSet
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-machines-api
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/r3dact3d/gitops'
    path: common-base
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
