---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-appsets
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'gitops-appsets'
    spec:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          valueFiles:
            - '../../blinker19/values.yaml'
        repoURL: 'https://github.com/r3dact3d/gitops'
        path: common-base/gitops-appsets
        targetRevision: HEAD
