---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-deploy
  namespace: openshift-operators
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: common-base/openshift-machine-api/
    repoURL: https://github.com/r3dact3d/gitops
    targetRevision: ocp4
