---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            certs: true 
  template:
    metadata:
      name: '{{name}}-cert-manager'
    spec:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      project: default
      source:
        path: common-base/cert-manager
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
        helm:
          valueFiles:
            - ../../{{name}}/values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
