---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-certificates-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            env: demo
  template:
    metadata:
      name: '{{name}}-openshift-certificates'
    spec:
      destination:
        namespace: openshift-operators
        server: '{{server}}'
      project: default
      source:
        path: common-base/openshift-certificates
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
        helm:
          valueFiles:
            - '../../{{name}}/values.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
