---
kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: api-cert-secret
  namespace: openshift-config
data:
  tls.crt: {{ .Values.apiTlsCrt }}
  tls.key: {{ .Values.apiTlsKey }}
type: kubernetes.io/tls
