---
apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: instance 
  namespace: openshift-logging 
spec:
  outputs:
   - name: splunk-server-secure 
     type: "fluentdForward"
     url: https://prd-p-iv34h.splunkcloud.com
     secret:
       name: testsecret
  inputs: 
   - name: my-app-logs
     application:
        namespaces:
        - hello-houston-blinker-dev
        - openshift-file-integrity
  pipelines:
   - name: container-logs
     inputRefs:
     - application
     outputRefs:
     - splunk-server-secure

