---
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed"  
  collection:
    logs:
      type: "fluentd"  
      fluentd:
        nodeSelector:
          node.openshift.io/os_id: "rhcos"
        tolerations:
        - key: infra
          value: reserved
          effect: NoSchedule
        resources:
          limits: 
            memory: 736Mi
          requests:
            cpu: 100m
            memory: 736Mi
        token: af3a7872-4df1-4493-8a6d-9a3646e574fa
