apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/r3dact3d/gitops.git
        revision: HEAD
        files:
        - path: "git-server/git-generator-files-discovery/cluster-config/dumb/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
      source:
        repoURL: 'https://github.com/r3dact3d/animated-bassoon'
        targetRevision: '{{revision}}'
        path: 'app/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        #server: '{{cluster.address}}'
        namespace: guestbook
