---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-rss
spec:
  generators:

  - clusters:
      selector:
        matchLabels:
          env: 'test'
      values:
        revision: HEAD
        env: test

  template:
    metadata:
      name: 'namespace-{{name}}'
    spec:
      source:
        repoURL: 'https://github.com/r3dact3d/gitops'
        targetRevision: HEAD
        path: 'common-base/special_namespace'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'hello-houston-{{name}}'
