---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bdg
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: 'dev'
      values:
        revision: hotfix-linter
  - clusters:
      selector:
        matchLabels:
          env: 'demo'
      values:
        revision: HEAD
  template:
    metadata:
      name: '{{name}}-bgd'
      namespace: '{{name}}-bgd'
    spec:
      source:
        repoURL: 'https://github.com/christianh814/bgd'
        targetRevision: HEAD
        path: app/overlays/default/
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'bgd-{{name}}'
