---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-onboarding 
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproij.io/secret-type: cluster
          local: only
  template:
    metadata:
      name: 'cluster-onboarding'
    spec:
      source:
        repoURL: 'https://github.com/r3dact3d/gitops' 
        targetRevision: HEAD
        path: cluster-onboarding
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'openshift-gitops'
