---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-monitoring-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            env: infra
  template:
    metadata:
      name: '{{name}}-openshift-monitoring'
    spec:
      destination:
        namespace: openshift-monitoring
        server: '{{server}}'
      project: default
      source:
        path: common-base/openshift-monitoring
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
