---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-openshift
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: 'dev'
      values:
        revision: HEAD # staging clusters use HEAD branch
  - clusters:
      selector:
        matchLabels:
          env: 'prod'
      values:
        revision: stable
  template:
    metadata:
      name: '{{name}}-hello-openshift'
      namespace: '{{name}}-hello-openshift'
    spec:
      source:
        repoURL: 'https://github.com/r3dact3d/studious-happiness'
        targetRevision: '{{values.revision}}'
        path: webserver/base
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'hello-{{name}}'
